### ISSUE TITLE
Code Anomaly Detection in multivariate Sensor Data

### ISSUE THREAD

**Issue by scheu-dev** [sacry-/DeepLearningGroup#1]
The Thesis above is very interesting for my own master thesis at HU Berlin. Do you happen to know Paul Assendorp? I would like to ask whether the code used in the Thesis might by publicly available or he would be willing to share it with me, for the purpose of my thesis.

Thanks in Advance.
Best Marc

**Comment by sacry-** [comment]
@marceduc hey, the thesis can be found here: https://users.informatik.haw-hamburg.de/~ubicomp/arbeiten/master/assendorp.pdf and I believe his Github profile is @pasndrp . Maybe he will answer here directly.

**Comment by pasndrp** [comment]
Hi Marc,

The code and dataset used for the thesis is unfortunately not publicly available, as it contains internal information from an industry partner. However, I'd be happy to answer questions regarding the thesis if that helps. You can email me at: p.assendorp@gmail.com

**Comment by scheu-dev** [comment]
Thanks for the quick replies. I ll use a similar AutoEncoder in my Thesis to detect driving anomalies. I was wondering about some general Implementation aspects, but I think this is resolved for now. Thanks a lot for the offer! I ll come back to it if I get stuck with more specific questions. :)
